--------------------------------------------------------------------------------
 
-- SETUP DE CRIACAO DO UCONTADB NO PSTGRESSQL NO HEROKU

--------------------------------------------------------------------------------

-- VARIAVEIS
CREATE TABLE TB_BILL (
	COD_BILL INTEGER not NULL,
	DATE_BILL DATE NOT NULL, 
	DESCRIPTION VARCHAR(200) NOT NULL, 
	VALUE DOUBLE PRECISION NOT NULL, 
	CATEGORY INTEGER NOT NULL
  );

CREATE TABLE TB_CATEGORY (
	COD_CATEGORY SERIAL NOT NULL, 
	NAME VARCHAR(200) NOT NULL
	);

-- Sequences
CREATE SEQUENCE SEQ_CF_COD_BILL INCREMENT 1 START 10 NO CYCLE;
CREATE SEQUENCE SEQ_CF_COD_CATEGORY INCREMENT 1 START 10 NO CYCLE;

-- Pks
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_COD_CATEGORY PRIMARY KEY (COD_CATEGORY);
ALTER TABLE TB_BILL ADD CONSTRAINT PK_COD_BILL PRIMARY KEY (COD_BILL);

-- FKs
ALTER TABLE TB_BILL ADD CONSTRAINT FK_COD_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(COD_CATEGORY);
	





