-- Tabelas
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE TB_BILL (
	COD_BILL SERIAL NOT NULL,
	DATE_BILL DATE NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	VALUE DOUBLE PRECISION NOT NULL,
	CATEGORY INTEGER NOT NULL
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE TB_CATEGORY (
	COD_CATEGORY SERIAL NOT NULL,
	NAME VARCHAR(200) NOT NULL
	);

-- Pks
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_COD_CATEGORY PRIMARY KEY (COD_CATEGORY);
ALTER TABLE TB_BILL ADD CONSTRAINT PK_COD_BILL PRIMARY KEY (COD_BILL);

-- FKs
ALTER TABLE TB_BILL ADD CONSTRAINT FK_COD_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(COD_CATEGORY);



